# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/robotics/autonomous_driving_links/point/point/open3d_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/robotics/autonomous_driving_links/point/point/open3d_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robotics/autonomous_driving_links/point/point/open3d_cpp/CMakeFiles /home/robotics/autonomous_driving_links/point/point/open3d_cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robotics/autonomous_driving_links/point/point/open3d_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TestVisualizer

# Build rule for target.
TestVisualizer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestVisualizer
.PHONY : TestVisualizer

# fast build rule for target.
TestVisualizer/fast:
	$(MAKE) -f CMakeFiles/TestVisualizer.dir/build.make CMakeFiles/TestVisualizer.dir/build
.PHONY : TestVisualizer/fast

#=============================================================================
# Target rules for targets named Segmentator

# Build rule for target.
Segmentator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Segmentator
.PHONY : Segmentator

# fast build rule for target.
Segmentator/fast:
	$(MAKE) -f CMakeFiles/Segmentator.dir/build.make CMakeFiles/Segmentator.dir/build
.PHONY : Segmentator/fast

Segmentator.o: Segmentator.cpp.o

.PHONY : Segmentator.o

# target to build an object file
Segmentator.cpp.o:
	$(MAKE) -f CMakeFiles/Segmentator.dir/build.make CMakeFiles/Segmentator.dir/Segmentator.cpp.o
.PHONY : Segmentator.cpp.o

Segmentator.i: Segmentator.cpp.i

.PHONY : Segmentator.i

# target to preprocess a source file
Segmentator.cpp.i:
	$(MAKE) -f CMakeFiles/Segmentator.dir/build.make CMakeFiles/Segmentator.dir/Segmentator.cpp.i
.PHONY : Segmentator.cpp.i

Segmentator.s: Segmentator.cpp.s

.PHONY : Segmentator.s

# target to generate assembly for a file
Segmentator.cpp.s:
	$(MAKE) -f CMakeFiles/Segmentator.dir/build.make CMakeFiles/Segmentator.dir/Segmentator.cpp.s
.PHONY : Segmentator.cpp.s

TestVisualizer.o: TestVisualizer.cpp.o

.PHONY : TestVisualizer.o

# target to build an object file
TestVisualizer.cpp.o:
	$(MAKE) -f CMakeFiles/TestVisualizer.dir/build.make CMakeFiles/TestVisualizer.dir/TestVisualizer.cpp.o
.PHONY : TestVisualizer.cpp.o

TestVisualizer.i: TestVisualizer.cpp.i

.PHONY : TestVisualizer.i

# target to preprocess a source file
TestVisualizer.cpp.i:
	$(MAKE) -f CMakeFiles/TestVisualizer.dir/build.make CMakeFiles/TestVisualizer.dir/TestVisualizer.cpp.i
.PHONY : TestVisualizer.cpp.i

TestVisualizer.s: TestVisualizer.cpp.s

.PHONY : TestVisualizer.s

# target to generate assembly for a file
TestVisualizer.cpp.s:
	$(MAKE) -f CMakeFiles/TestVisualizer.dir/build.make CMakeFiles/TestVisualizer.dir/TestVisualizer.cpp.s
.PHONY : TestVisualizer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TestVisualizer"
	@echo "... Segmentator"
	@echo "... Segmentator.o"
	@echo "... Segmentator.i"
	@echo "... Segmentator.s"
	@echo "... TestVisualizer.o"
	@echo "... TestVisualizer.i"
	@echo "... TestVisualizer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

